spring.application.name: WaiChat
spring:
  datasource:
    url: jdbc:mysql://116.62.163.226:3306/waichat
    username: root
    password: AXem8bxnCXEeYzXm
    driver-class-name: com.mysql.cj.jdbc.Driver
